framework:
    secret: '%env(APP_SECRET)%'

    session:
        handler_id: App\Service\CustomSessionHandler
        cookie_secure: auto
        cookie_lifetime: 86400       # 0 = bis Browser geschlossen
        cookie_samesite: lax
        cookie_httponly: true
        gc_maxlifetime: 86400
        gc_probability: 1

    trusted_hosts:
        - '^admin\.joormann-media\.local$'
        - '^admin\.joormann-media\.de$'
        - '^gaming\.joormann-media\.local$'
        - '^gaming\.joormann-media\.de$'
        - '^tekath\.joormann-media\.local$'
        - '^tekath\.joormann-media\.de$'
        - '^pma\.joormann-media\.local$'
        - '^pma\.joormann-media\.de$'

        # XXLPRINT lokale Domains
        - '^admin\.xxlprint-wesel\.local$'
        - '^xxlprint-wesel\.local$'
        - '^www\.xxlprint-wesel\.local$'

        # ðŸ‘‰ HIER: der Ã¶ffentliche Host
        - '^admin\.xxlprint-wesel\.de$'

        # Wenn du die Hauptdomain ebenfalls erlauben willst
        - '^xxlprint-wesel\.de$'
        - '^www\.xxlprint-wesel\.de$'





    http_client:
        scoped_clients:
            ortungslogistik.client:
                base_uri: 'https://www.ortungslogistik.de/api/'
                headers:
                    Accept: 'application/json'
                    X-Requested-With: 'XMLHttpRequest'
                    Referer: 'https://www.ortungslogistik.de/Live'
